Repository LKaio16/indiestream-app, pull requests merged in 2025-03, with the labels that each got.

#85 feat: ajustar funcionalidade e estilização tela projetos
  lib/projetos_screen.dart
Labels: enhancement

#88 fix: remover barra de pesquisa duplicada
  lib/home_screen.dart
Labels: bug

#90 Feature/user auth
  lib/auth_service.dart
  lib/login_screen.dart
  pubspec.yaml
Labels: enhancement

#91 feat: ajustar funcionalidade e estilização tela criar projetos
  lib/projeto_create_screen.dart
  lib/projetos_screen.dart
Labels: duplicate, enhancement

#92 feature: criando pagina de configuracao do feature: criando pagina de configuracao do aplicativo
  Documentação/SQL/indie_stream.sql
  lib/auth_service.dart
  lib/config_page.dart
  lib/home_screen.dart
  lib/login_screen.dart
  lib/pessoas_screen.dart
  lib/projeto_create_screen.dart
  lib/projetos_screen.dart
  pubspec.lock
  pubspec.yaml
  seeder_script/main.py
Labels: enhancement
